### ISSUE TITLE
Pictomancer's "Starry Muse" queuing problem

### ISSUE THREAD

**Issue by Lornvene** [cairthenn/Redirect#61]
Casting any GCD, press "Starry Muse" while **during** the cast, the action do not execute after finished casting.

1. when"Allow these actions to queue - Ground targeted actions" enabled, error message says "Target is not in range" or "Target is out of range"
2. when disabled, error message says "Cannot use while casting"
3. ty for fixing the previous ground targeting problem <3

![pic gif - Copy](https://github.com/cairthenn/Redirect/assets/41856088/37de4893-599c-4acb-98b2-f9f172bf30dc)

**Comment by cairthenn** [comment]
Starry Muse is treated as a ground action due to the circle of paint and will not queue as normal by the game design. The default "ground targeted actions as mouseover" option is currently thinking that it can place the action somewhere other than the character's feet. 

I have a fix for this soon, but you can either mouseover your character frame when pressing it, or temporarily disable that setting and manually select mouseover options for ground targeted actions.

**Comment by cairthenn** [comment]
Seems SE fixed the queueing behavior in the hotfix this morning. 1.2.4.0 will fix the "Target is not in range" error whenever the Dalamud PR is approved, so I'm closing this for now. Feel free to create another issue if any problems persist after updating
